mkdocs.yml

There are several code blocks annotated with language tags, but no syntax highlighting is used since the "codehilite" extension is not enabled.

Add codehilite markdown extension to mkdocs

---

pkg/services/pushover/pushover.go
pkg/services/pushover/pushover_config.go
pkg/services/pushover/pushover_test.go
shoutrrr.go

Also fixes the multi-device support that was implied by the `devices` parameter, but wasn't actually implemented.

feat(pushover): add title and priority parameters

---

pkg/router/router.go

Otherwise the method would panic trying to get the length of services..
Having no senders is only possible if you didn't check the errors from `CreateSender()` but I think avoiding a panic is whortwhile anyway.

Return error when sending with no senders created

---

.github/workflows/release.yml
Dockerfile

Includes the CA cert bundle from cURL into the docker image.  
Fixes #47

fix(docker): add CA cert bundle to docker image

---

docs/services/discord.md
docs/services/overview.md

The ID is not actually the channel, it's the ID of the webhook – all webhooks are technically bot users under the hood, and this is their user ID (snowflake)

Correct the ID part of webhook

---

go.mod
pkg/services/rocketchat/rocketchat.go
pkg/services/rocketchat/rocketchat_config.go
pkg/services/rocketchat/rocketchat_test.go

Closes: https://github.com/containrrr/shoutrrr/issues/76
Closes: https://github.com/containrrr/shoutrrr/issues/71
Added custom port option for --url rocketchat://Host:Port/....

added custom port option for rocketchat

---

pkg/services/rocketchat/rocketchat.go
pkg/services/rocketchat/rocketchat_config.go

I removed TrimPrefix as discussed here: [https://github.com/containrrr/shoutrrr/pull/83#discussion_r523826228](https://github.com/containrrr/shoutrrr/pull/83#discussion_r523826228)
I added logic to print the http response body if response status code is different then 200. Errors returned by the server are now visible, for example:
`error invoking send: notification failed: 404 {"success":false,"error":"Invalid integration id or token provided."}%    `

do not rewrite channel name without hashes

---

pkg/services/mattermost/mattermost.go

Fixes: https://github.com/containrrr/shoutrrr/issues/93
- Before:
```
kubectl logs pod/kured-kj4mv -n kube-system
time="2020-12-09T19:12:59Z" level=warning msg="Deprecated flag(s). Please use --notify-url flag instead."
time="2020-12-09T19:12:59Z" level=info msg="Kubernetes Reboot Daemon: master-da7f425"
time="2020-12-09T19:12:59Z" level=info msg="Node ID: minikube-m02"
time="2020-12-09T19:12:59Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2020-12-09T19:12:59Z" level=info msg="Lock TTL not set, lock will remain until being released"
time="2020-12-09T19:12:59Z" level=info msg="Reboot Sentinel: /var/run/reboot-required every 20s"
time="2020-12-09T19:12:59Z" level=info msg="Blocking Pod Selectors: []"
time="2020-12-09T19:12:59Z" level=info …
```

added errocheck to avoid segfault due to nil http.response *service.mattermost

---

pkg/services/smtp/smtp.go
pkg/services/smtp/smtp_config.go
pkg/services/smtp/smtp_encmethod.go
pkg/services/smtp/smtp_test.go

Add SMTPS (implicit TLS) support for SMTP.
Use implicit TLS by default if port is set to `465`, configurable by setting the `Encryption` field.
Fixes #68

feat(smtp): add support for implicit TLS

---

cli/cmd/verify/verify.go

fix the output of `verify` command to display the fields in alphabetical order.
also adds a newline after the error message on failed verifications

fix(verify): display fields in sorted order

---

pkg/format/prop_key_resolver.go

hey
it seems like for the 4 services that use `UpdateConfigFromParams`, the provided config is a pointer 
so with this exampe
```go
package main
import (
"github.com/containrrr/shoutrrr"
"github.com/containrrr/shoutrrr/pkg/types"
)
func main() {
sen, _ := shoutrrr.CreateSender("smtp://a:b@com:587?fromAddress=_&toAddresses=_")
_ = sen.Send("Hello", &types.Params{
"subject": "Hello",
})
}
```
was hitting this panic:
```
panic: reflect: call of reflect.Value.FieldByName on ptr Value                                                                                                                
goroutine 20 [running]:                                                                                                                                                       
reflect.flag.mustBe(...) …
```

use reflect.Indirect on Config for PropKeyResolver.set

---

docs/services/overview.md
docs/services/telegram.md
mkdocs.yml
pkg/services/telegram/telegram.go
pkg/services/telegram/telegram_config.go
pkg/services/telegram/telegram_internal_test.go
pkg/services/telegram/telegram_json.go
pkg/services/telegram/telegram_parsemode.go
pkg/services/telegram/telegram_test.go

Adds three relevant options for the telegram service to be configured using either query variables or params.
Fixes #98: Add `&preview=no` to the query string to disable previews

feat(telegram): add more config options and tests

---

cli/cmd/send/send.go
pkg/format/format_query.go
pkg/format/formatter.go
pkg/format/prop_key_resolver.go
pkg/services/smtp/smtp_config.go
pkg/services/smtp/smtp_test.go

This will add support for multiple key names in the `key` tag (separated by commas), which allows all services to use the `title` key as an alias (or as the primary key).
This also adds said alias to the SMTP service for the `subject` field and a `title` argument to the `send` command.
Fixes #30

feat: add standard title field

---

pkg/services/slack/slack.go
pkg/services/slack/slack_test.go

ref: https://github.com/containrrr/watchtower/issues/758

fix(slack): dont panic on send http errors

---

pkg/services/gotify/gotify.go
pkg/services/gotify/gotify_config.go
pkg/services/gotify/gotify_test.go

This adds the `title` and `priority` fields to the config and URL (previously only settable with params).
It also adds support for disabling TLS for non-https servers.
Ref: https://github.com/containrrr/watchtower/issues/761

fix(gotify): use pkr for fields to make them settable from url

---

pkg/services/pushover/pushover.go
pkg/services/pushover/pushover_config.go
pkg/services/pushover/pushover_test.go

,..and don't skip sending if `devices` is not provided

fix(pushover): send all devices in single request

---

pkg/generators/xouath2/xoauth2.go
pkg/services/smtp/smtp.go
pkg/services/smtp/smtp_authtype.go
pkg/services/smtp/smtp_config.go
pkg/services/smtp/smtp_encmethod.go

- Add missing required `Date: ` header
- Make `AuthTypes` and `EncMethods` enum helpers public

fix(smtp): add date header and make enums public

---

cli/cmd/exit_codes.go
internal/util/cobra.go
pkg/format/formatter.go
pkg/generators/basic/basic.go
pkg/generators/router.go
pkg/generators/xouath2/xoauth2.go
pkg/services/rocketchat/rocketchat.go
pkg/services/smtp/smtp.go
pkg/services/smtp/smtp_encmethod.go
pkg/services/standard/standard_failures.go
pkg/types/generator.go
pkg/types/service_config.go

Fixes the various errors that show up when running `golint ./...` locally, effectively hiding any relevant problems in the noise.

fix: resolve outstanding golint errors

---

pkg/router/router.go
pkg/router/router_suite_test.go
pkg/types/custom_url_config.go

This will allow services to opt in to supporting the `service+custom` URL schema, which can be used for simplifying the setup in  basic scenarios, or to support multiple URL formats.
Example usage by `teams` in #117 :
User get a webhook URL from Teams, and simply prepends `teams+` to the URL to make it a shoutrrr URL:
`teams+https://outlook.office.com/webhook/12345....`

feat(router): add support for custom service URLs

---

cli/cmd/send/send.go

The `send` cli command uses `StringSlice` for the URL argument which will split the input string by ",". This prevents commas from being used in service URLs which is perfectly valid from other usages.
This will change URL to instead use `StringArray`, which will keep the input intact, but supplying it multiple times adds to the array.
Example:
```
shoutrrr send -u gotify://localhost/token -u logger:// -m Message -t Title
or
shoutrrr send -u gotify://localhost/token Message -u logger:// -t Title
```
(first and second non-flag argument are still URL and Message respectively)

fix(send): use StringArray flag for url to not split on commas

---

pkg/services/gotify/gotify.go
pkg/services/gotify/gotify_config.go
pkg/services/gotify/gotify_test.go

feat(gotify): add support for gotify URL path

---

pkg/services/slack/slack.go
pkg/services/slack/slack_config.go
pkg/services/slack/slack_json.go
pkg/services/slack/slack_test.go
pkg/services/slack/slack_token.go

- Use legacy `attachments` due to the color support
- Use the normal text field as `title`
- Allow color and title to be set using query and params
- Don't override Bot name by default

fix(slack): use attachments and add title and color fields

---

pkg/router/router_suite_test.go
pkg/services/teams/teams.go
pkg/services/teams/teams_config.go
pkg/services/teams/teams_json.go
pkg/services/teams/teams_test.go
pkg/services/teams/teams_token.go

- Change the URL format (with support for reading the old format) to one that is easier to type by hand
- Add title and color fields
- Use `sections` for messages (align with common bot output)
- Correctly parse and test webhook URLs
- Add groundwork for rich API

fix(teams): use better URL format and nicer output

---

pkg/services/teams/teams.go
pkg/services/teams/teams_config.go

Remove unused and untested config constructor/setter and use the slower, but more reliable parseAndVerify for public constructor

fix(teams): remove unsafe config constructor

---

pkg/services/hangouts/hangouts.go
pkg/services/hangouts/hangouts_config.go
pkg/services/hangouts/hangouts_test.go
pkg/services/smtp/smtp_encmethod.go
pkg/services/telegram/telegram_json.go
pkg/services/zulip/zulip.go
pkg/services/zulip/zulip_config.go
pkg/services/zulip/zulip_test.go

Generate compatibility fixes

---

pkg/format/format.go
pkg/format/format_test.go
pkg/format/formatter.go
pkg/types/config_prop.go

Adds additional configuration field types for service configs.
Ref #73

feat: add support for struct and map fields

---

docs/services/discord.md

The added props to the discord service where not documented. This adds the useful ones to the docs (the additional colors cannot be used in any meaningful way right now, so documenting them would just lead to confusion).

docs(discord): add props usage

---

mkdocs.yml

From mkdocs [documentation](mkdocs.org/user-guide/configuration/#edit_uri):
> Note
> 
> On a few known hosts (specifically GitHub, Bitbucket and GitLab), the edit_uri is derived from the 'repo_url' and does not need to be set manually. Simply defining a repo_url will automatically populate the edit_uri configs setting.
> 
> For example, for a GitHub- or GitLab-hosted repository, the edit_uri would be automatically set as edit/master/docs/ (Note the edit path and master branch).
> 
> For a Bitbucket-hosted repository, the equivalent edit_uri would be automatically set as src/default/docs/ (note the src path and default branch).
> 
> To use a different URI than the default (for example a different branch), simply set the edit_uri to your desired string. If you do not want any "edit URL …

Set different default branch for mkdocs edit

---

pkg/services/gotify/gotify.go
pkg/services/gotify/gotify_test.go

if `DisableTLS` is specified, disable TLS verification as well since the default configuration of Gotify redirects HTTP to HTTPS, rendering the schema change moot

fix(gotify): include redirects when tls is disabled

---

pkg/services/discord/discord_json.go
pkg/services/discord/discord_test.go

fix(discord): dont create meta embed when empty

---

docs/services/overview.md
mkdocs.yml
pkg/format/format_query.go
pkg/format/format_query_test.go
pkg/format/format_test.go
pkg/format/formatter_test.go
pkg/format/prop_key_resolver.go
pkg/format/prop_key_resolver_test.go
pkg/router/servicemap.go
pkg/services/generic/generic.go
pkg/services/generic/generic_config.go
pkg/services/generic/generic_test.go
pkg/types/params.go

This adds a custom webhook service that just posts the `message` to the URL that corresponds to the URL.
To use it with another format, set the `template` query field (`generic://example.com/api/webhook?template=TEMPLATE_ID` or pass it as a param to `Send`:
```go
err = service.Send("Message", &types.Params{"template": "TEMPLATE_ID"})
```
The templates are loaded into the service by using either
```go
err := service.SetTemplateString("TEMPLATE_ID", `{{.message}}`)
```
or
```go
err := service.SetTemplateFile("TEMPLATE_ID", "/path/to/template.file")
```
Where `TEMPLATE_ID` can be anything.

feat(service): add generic webhook service

---

docs/services/matrix.md
docs/services/overview.md
pkg/router/servicemap.go
pkg/services/matrix/matrix.go
pkg/services/matrix/matrix_api.go
pkg/services/matrix/matrix_client.go
pkg/services/matrix/matrix_config.go
pkg/services/matrix/matrix_test.go

feature: add matrix service

---

pkg/router/router.go
pkg/services/discord/discord.go
pkg/services/gotify/gotify.go
pkg/services/hangouts/hangouts.go
pkg/services/ifttt/ifttt.go
pkg/services/join/join.go
pkg/services/logger/logger.go
pkg/services/mattermost/mattermost.go
pkg/services/opsgenie/opsgenie.go
pkg/services/pushbullet/pushbullet.go
pkg/services/pushover/pushover.go
pkg/services/rocketchat/rocketchat.go
pkg/services/slack/slack.go
pkg/services/smtp/smtp.go
pkg/services/standard/standard_logger.go
pkg/services/teams/teams.go
pkg/services/telegram/telegram.go
pkg/services/xmpp/xmpp.go
pkg/services/zulip/zulip.go
pkg/types/service.go
pkg/types/std_logger.go
shoutrrr.go

Previously the public api only contained a constructor that did not set up logging, and even worse, adding logging after calling `shoutrrr.CreateSender` only applied said logging to any subsequently added services. Which of course there were no API to do either.
So, a new public API constructor was added using the name `NewSender` that takes a logger as it's first argument (can be nil), and also moves the adding/initializing of services to a separate method that can be called after init.
This also replaces the stdlib `log.Logger` with an interface that can be implemented by other logging providers.

fix(api): logging via interface and set/update using api

---

pkg/services/discord/discord.go
pkg/services/discord/discord_config.go
pkg/services/discord/discord_test.go

Note: Breaking change for anything explicitly passing a config struct to the discord service (which should normally never be the case).
fixes #156

fix(discord): rename channel into webhook ID

---

pkg/services/gotify/gotify.go
pkg/services/gotify/gotify_test.go
pkg/services/ifttt/ifttt_config.go
pkg/services/opsgenie/opsgenie.go
pkg/services/opsgenie/opsgenie_config.go
pkg/services/services_test.go
pkg/services/telegram/telegram_config.go
pkg/services/telegram/telegram_test.go

~~Note: This intentionally includes tests that currently fail.~~
Service Compliance information moved to [wiki page](https://github.com/containrrr/shoutrrr/wiki/Service-compliance).
The general point of this PR is to add tests to make sure that all services comply with the first Service Compliance rule:
> Services should not fail to send messages when the title param is passed. The service does not need to use it in any specific way, but it should not return an error (unless failing for some other reason).
Added test resulted in the following services that did not pass:
- **Telegram**  
Supports Params? ✔ Yes!
Supports Title prop?  ⚫ No
Silently ignores title? ❌ Error: `title is not a valid config key [channels notification parsemode preview]`
- IFTT
Supports Params? ✔ Yes!
Uses title …

Assert service compliance

---

Dockerfile

If the entrypoint uses a relative path we are not able to set a different working directory, i.e. in Dockerfiles extending this.

Use absolute path for entrypoint in Dockerfile

---

pkg/services/discord/discord.go
pkg/services/discord/discord_config.go
pkg/services/discord/discord_json.go

Fixes Discord avatar override not being populated in the webhook payload. Also, this fixes the documentation name of the prop (and adds an alias for `avatarurl` which was listed in the docs previosuly).

fix: discord avatar override

---

.github/workflows/docs.yml
docs/overrides/main.html
docs/services/generic.md
docs/services/googlechat.md
docs/services/hangouts.md
docs/services/logger.md
docs/services/overview.md
mkdocs.yml

This adds multi-version support for the docs.
Currently the idea is to keep two versions of the documentation, referred to as "dev", created from `main:HEAD`, and "latest", created from `latest:HEAD`.
As soon as v0.5 is released, `latest` will point to `v0.5` and `v0.4` will be kept (but probably won't be updated anymore, hence no separate branch).
Fixes #177

docs: add multi-version support

---

pkg/services/slack/slack_config.go
pkg/services/slack/slack_json.go

- Added `thread_ts` field to Config and JSON 
- If thread  time stamp is supplied it will be sent as reply to message in a thread
- Reference https://api.slack.com/messaging/webhooks#threads

feat(slack): add thread/reply support

---

pkg/services/logger/logger.go
pkg/services/logger/logger_suite_test.go

this fixes an old bug where the logger, when combined with other services would add the param `message` to other services `Send()` (which they usually don't like).
also added tests for this and for normal operation.

fix(logger): avoid mutating passed params

---

cli/main.go
internal/meta/version.go
pkg/services/teams/teams.go
pkg/services/teams/teams_config.go
pkg/services/teams/teams_test.go
pkg/util/docs.go
pkg/util/partition_message_test.go
pkg/util/util_test.go
shoutrrr.go

fixes #187 
also includes static versioning information to allow linking docs in log messages

fix(teams): use correct path in webhook URL

---

pkg/router/router.go
pkg/router/router_suite_test.go

use a safe logging wrapper to avoid dereferencing a nil logger inside the router
fixes #186

fix(router): check for nil logger

---

cli/cmd/docs/docs.go
pkg/format/node.go
pkg/format/render_console_test.go
pkg/format/render_markdown.go
pkg/format/render_markdown_test.go
pkg/format/renderer.go
pkg/types/service_config.go

add tests for the expected output of the markdown and console renderers

test: add basic renderer tests

---

pkg/services/telegram/telegram_generator.go
pkg/services/telegram/telegram_generator_test.go
pkg/services/telegram/telegram_json.go
pkg/services/telegram/telegram_test.go

adds simple simulation of user interaction with telegram generator as a test

test(telegram): add generator test

---

generate-service-config-docs.sh
pkg/router/servicemap.go
pkg/router/servicemap_xmpp.go
pkg/services/googlechat/googlechat_test.go
pkg/services/join/join_test.go
pkg/services/mattermost/mattermost_config.go
pkg/services/mattermost/mattermost_test.go
pkg/services/xmpp/xmpp.go
pkg/services/xmpp/xmpp_config.go
pkg/services/xmpp/xmpp_test.go

this should bump up the test coverage a bit and fix some smaller serialization issues found while testing.
also, this disables the XMPP service (behind a build constraint) until it's deemed stable.

add general basic tests for services

---

docs/services/telegram.md
pkg/services/telegram/telegram_internal_test.go
pkg/services/telegram/telegram_json.go

feat(telegram): add title support

---

cli/cmd/docs/docs.go
docs/index.md
pkg/format/render_markdown.go
pkg/format/render_markdown_test.go

this will stop displaying the props description message when there are no query/param props to override.
at least solves the confusion in https://github.com/containrrr/shoutrrr/discussions/176

fix(docs): replace props desc when empty

---

pkg/services/smtp/smtp.go

The `MIME-Version` header sent by the smtp service contained a trailing `;` which seems to sometimes cause SpamAssassin to trigger the `BOGUS_MIME_VERSION` rule. Upon testing, this happened roughly 1/5 of the time, using the exact same message.
When removing the trailing `;`, I have not been able to trigger the rule.
fixes #200

fix(smtp): remove extra semi in mime header

---

generate-service-config-docs.sh

When the shoutrrr cli changed path, the documentation script was not updated to reflect this. This should restore the CI docs publishing.

ci: fix path to docs command

---

docs/services/telegram.md
pkg/format/render_console.go
pkg/format/render_console_test.go
pkg/services/matrix/matrix_client.go
pkg/services/matrix/matrix_config.go
pkg/services/telegram/telegram_config.go

Bulk updates to the documentation, clarifying `telegram` chats and matrix `URL` schema.
Also replaces the enum types in `shoutrrr docs` with a static `option` string when using the console renderer.

docs: update telegram, matrix and cli output

---

docs/services/mattermost.md
pkg/services/mattermost/mattermost.go
pkg/services/mattermost/mattermost_config.go
pkg/services/mattermost/mattermost_json.go
pkg/services/mattermost/mattermost_test.go

- What your PR contributes
Icon support on MatterMost:
```bash
./shoutrrr send -u 'mattermost://Argus@mattermost.example.io:443/xxxxxxxxxxx?icon_emoji=https%3A%2F%2Fraw.githubusercontent.com%2Fcontainrrr%2Fshoutrrr%2Fmain%2Fdocs%2Fshoutrrr-logotype.png' -m 'Icon Test'
./shoutrrr send -u 'mattermost://Argus@mattermost.example.io:443/xxxxxxxxxxx?icon_emoji=smiley' -m 'Icon Test'
```
- Which issues it solves
Moving my [Argus](https://github.com/release-argus/Argus/issues/33) project to use Shoutrrr. Really want to keep icon support!
- Tests that verify the code your contributing
I tried adding tests (and most of this code is copied from the Slack service), but couldn't get them to pass. Every other service that has query params seems to include the `title` param, but that's no supported on …

feat(mattermost): add support for icons

---

pkg/services/slack/slack_json.go
pkg/services/slack/slack_test.go

also removes last attachment if text is empty
fixes #238

fix(slack): limit attachments to 100

---

pkg/services/discord/discord.go
pkg/services/discord/discord_json.go
pkg/services/discord/discord_test.go
pkg/util/partition_message.go
pkg/util/partition_message_test.go

solves two panic conditions when using the discord service:
- sending an empty message without a title 
(fixes #239)
- sending a message with partitioning and a message that is a modulus of the configured chunk size 
(fixes #240)

discord message size fixes

---

internal/util/cobra.go
pkg/util/partition_message.go
shoutrrr/cmd/send/send.go

Allows piping the message to shoutrrr CLI:
```
$ some_command | shoutrrr slack://xoxb:123456789012-1234567890123-4mt0t4l1YL3g1T5L4cK70k3N@C0123456789 -
```
When the SHOUTRRR_URL environment variable has been set, you can also just pipe directly to shoutrrr, as the default option is to read from stdin. The main reason not to do this for normal usage is to prevent confusion upon invoking the command without any arguments as it waits for input from the attached console.
```
$ export SHOUTRRR_URL="slack://xoxb:123456789012-1234567890123-4mt0t4l1YL3g1T5L4cK70k3N@C0123456789"
$ some_command | shoutrrr
```

feat(cli): support reading message from stdin

---

pkg/util/partition_message.go
pkg/util/partition_message_test.go
pkg/util/util.go

The fix in #240 only addressed a specific issue, regarding repeated sequences of strings with no whitespace that were exact multiples of the maximum allow chunk size. It just moved the problem to another offset instead.
This does instead fix the real underlying issue and fixing one oddity with previous implementation (why a text string that were the same length as the chunk size would not fit inside one chunk).
Additionally, this includes a test iterating through 8000 text lengths and verifying the contents as well as the chunk sizes.
The general problem with the test is that the logic for calculating the expected sizes works the same way as the implementation. But matched with the unaligned limits and iteration, it should verify the logic sufficiently.
Fixes #244.

fix: text partitioning logic

---

internal/testutils/mockclientservice.go
pkg/services/gotify/gotify.go
pkg/services/gotify/gotify_config.go
pkg/services/gotify/gotify_json.go
pkg/services/gotify/gotify_test.go
pkg/services/services_test.go
pkg/util/jsonclient/jsonclient.go

This fixes a problem in gotify service, where it would not correctly handle a URL with only a token, but ending in `/`.
It also provides the full error messages as returned by the server upon failure.

fix(gotify): handle token ending in /

---

pkg/services/smtp/smtp_config.go
pkg/services/smtp/smtp_test.go

The [smtp docs](https://containrrr.dev/shoutrrr/v0.5/services/smtp/config/#queryparam_props) mention `UseStartTLS`, but it doesn't accept `usestarttls`, it wants `starttls`. As `UseStartTLS` is the Go var, it was probably designed to be `usestarttls` as the key, so here's a PR for that.
Thanks to @samcro1967 for spotting this in the issue for my PR that added Shoutrrr
https://github.com/release-argus/Argus/issues/33#issuecomment-1139113316
Wasn't sure about how/whether you'd want to keep support for `starttls` for a while as it would show in the docs if I put it under keys, right?

fix(smtp): use `usestarttls` (match the docs)

---

docs/services/telegram.md
pkg/services/telegram/telegram_generator.go
pkg/services/telegram/telegram_generator_test.go
pkg/services/telegram/telegram_json.go

The current docs regarding telegram channel _names_ only applies to _public_ channels. Addressing private channels is not possible using the described `@channelname` syntax.
This PR fixes the documentation regarding this, and makes the telegram generator display private channels correctly (instead of just calling them `@`). 
Fixes #249

fix(telegram): update docs and generator for private channels

---

docs/services/generic.md

Adds some basic usage information that is missing from the `generic` service.

docs(generic): add basic usage info

---

docs/services/generic.md
internal/meta/version.go
pkg/services/generic/generic.go
pkg/services/generic/generic_config.go
pkg/services/generic/generic_test.go

This adds some additional functionality to the `generic` service to make it a bit more useful.
You can now supply the template as `json` to format the `message` and `title` as a simple JSON-object. Combined with the ability to rename the keys in the payload, it should add compatibility with at least a few know services.
ref #256

feat(generic): add builtin JSON tpl

---

internal/failures/failure.go
internal/testutils/textconfaker.go
pkg/services/smtp/smtp.go
pkg/services/smtp/smtp_config.go
pkg/services/smtp/smtp_failures.go
pkg/services/smtp/smtp_test.go

Adds the `clienthost` property that can be used to send a specific host name during the initial `HELO/EHLO` greeting phase. It can also be set to `auto` to use the OS hostname as the client host name.
Solves connections to `smtp-relay.gmail.com` which soft-requires the name to be non-generic:
[support.google.com/a/answer/2956491](https://support.google.com/a/answer/2956491?hl=en#:~:text=We%20recommend%20that%20servers%20presents%20unique%20identifiers%20in%20the%20HELO%20or%20EHLO%20arguments%20during%20SMTP%20connections.%20For%20example%2C%20use%20your%20domain%20name%20or%20the%20server%20name%2C%20instead%20of%20generic%20identifiers%20such%20as%20localhost%20or%20smtp%2Drelay.gmail.com.)
This will also handle and log when the initial response from the server isn't valid, giving a …

feat(smtp): add support for custom client host

---

go.mod
pkg/services/bark/bark.go
pkg/services/discord/discord_test.go
pkg/services/matrix/matrix.go
pkg/services/matrix/matrix_client.go
pkg/services/pushbullet/pushbullet.go
pkg/services/pushbullet/pushbullet_json.go
pkg/services/pushover/pushover.go
pkg/services/rocketchat/rocketchat.go
pkg/services/slack/slack.go
pkg/services/teams/teams_config.go
pkg/util/jsonclient/jsonclient.go
shoutrrr/cmd/send/send.go

In #143 we briefly discussed parsing error messages and whether wrapping errors could help with that.
This is a somewhat simple change to do that. We could probably do more by rewriting stuff to get more and better error messages.
This change tries to stay backward compatible. But notice:
- We bump the required go to version 1.13 because we cannot wrap error in earlier versions. 1.12 is a long time ago, so I hope this will be fine.
- Refactor the Pushbullet implementations `ErrorResponse` to implement an error interface. This requires renaming an exported field. I cannot really see how anyone could use the exported field, though, so I think this is safe to do.

feat: wrap errors

---

.github/dependabot.yml
.github/workflows/docs.yml
.github/workflows/main.yml
.github/workflows/post-release.yml
.github/workflows/release.yml
go.mod

GitHub Actions only tested the build using go 1.13 (which has been unsupported by the Go team for more than two years).
Introduce a build matrix testing all versions from the lowest supported by shoutrrr to the newest released by the Go team (shamelessly using my own [Go Version Action](https://github.com/marketplace/actions/go-version-action)).
The matrix test showed the code didn't compile in go1.12 anymore. 
The release action built the version for release with go 1.13. From now, we'll use the latest go release.
The old version used node 12 which is [deprecated by GitHub Actions](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
Instead of installing goreleaser by ourselves, we'll let the [goreleaser …

Cleanup and improve GitHub Actions

---

internal/dedupe/dedupe.go
internal/dedupe/dedupe_test.go
shoutrrr/cmd/send/send.go

It doesn't make much sense to send a message to the same service twice.
It's probably not likely that a user will make the mistake by adding the same service twice by adding it twice on the command
line (`shoutrrr send --url=my://service --url=my://service`), but in a script or Docker setup it could happen accidentally using an environment variable like this:
```bash
export SHOUTRRR_URL=my://service
shoutrrr --url=${SHOUTRRR_URL}
```
This has happened to me in a Docker setup. And I'm not too proud to admit that it took me a long time before I figured out why each message was duplicated...

Remove duplicate URLs so we don't send to the same service twice

---

.github/workflows/release.yml
.gitignore
README.md
snap/snapcraft.yaml

Given how good and easy the CLI has become to use, it only makes sense for it to also be available as a snap on the snapstore. I've gone ahead and registered the snap name already and published a revision on the stable track.
This PR moves the ownership of the snap packing spec to the containrrr team.
[Snapstore Entry](https://snapcraft.io/shoutrrr)

Make the cli available as a snap

---

pkg/services/generic/generic.go
pkg/services/generic/generic_test.go
pkg/types/params.go

The params passed to the services should not be mutated. This unfortunately wasn't true for `generic`, so this PR rectifies that.
fixes #309

fix(generic): prevent mutation of params

---

internal/testutils/eavesdropper.go
internal/testutils/logging.go
internal/testutils/testutils_test.go
internal/testutils/textconfaker.go
pkg/services/smtp/smtp.go
pkg/services/smtp/smtp_config.go
pkg/services/smtp/smtp_test.go

This PR allows the SMTP service to treat `+` in e-mail addresses as literal `+` characters instead of spaces. Since spaces are not allowed in e-mail addresses as per RFC-5322, we can just assume that the user intended the `+`s to be interpreted literally.
Fixes #306

fix(smtp): dont treat plus in addresses as space

---

docs/examples/generic.md
docs/services/generic.md
docs/services/generic/examples.md
mkdocs.yml

This adds the information provided by @jeffcrum1 as an example of how to use the generic service with home assistant. It also adds a note about the `template=json` not being usable with the `generic+` helper.

docs(generic): add home assistant example

---

docs/services/telegram.md
pkg/services/telegram/telegram_internal_test.go
pkg/services/telegram/telegram_json.go

Reference: https://core.telegram.org/bots/api#sendmessage
closes #361

feat(telegram): add support for message_thread_id

---

docs/services/matrix.md

Updates the docs to include a note on the caveat with `title` not being used for Matrix messages.
resolves #335

Update matrix docs to mention `title` caveat

---

pkg/services/ifttt/ifttt.go

Originally, shoutrrr sees only http status code 204 as a successful response from IFTTT webhook service.
However, http status code 200 should be also seen has a successful response.
This prevents an incorrect error log from generating.

fix(ifttt): treat all 2xx http responses as success

---

docs/services/generic.md
pkg/services/generic/custom_query.go
pkg/services/generic/generic.go
pkg/services/generic/generic_config.go
pkg/services/generic/generic_test.go

Add support for `@header=value` and `$data=value` query parameters for the generic service.
This also enables support for header-based authentication, i.e. by using `?@authorization=Bearer+TOKEN`.
Fixes #365
Fixes #366

feat(generic): extra data and custom headers

---

pkg/services/bark/bark.go

fix the missing param `url` for Bark service

fix(bark): fix param url

---

pkg/services/smtp/smtp.go

Backport of d3439eb169948095c48a66ca7ed3147c9e3e08b2 to main.

hotfix(email): set default client host

---

pkg/services/slack/slack.go
shoutrrr/cmd/verify/verify.go

This PR fixes a few minor issues I noticed when checking the code.

fix: fix an incorrect printf and add a missing error check

---

CONTRIBUTING.md
README.md
build.sh

This PR fixes a typo and updates various instructions that I believe are outdated.

docs: fix outdated documentation
